apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-autoscaler
  namespace: default  # Adjust as needed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-autoscaler-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-autoscaler-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-autoscaler-role
subjects:
  - kind: ServiceAccount
    name: pod-autoscaler
    namespace: default
